### ISSUE TITLE
npm install fails and npm start fails on node 7.5.0 with npm v.4.1.2_EDIT I got it to work

### ISSUE THREAD

**Issue by S3curityPlu5** [training4developers/using-react-with-redux#1]
npm ERR! Windows_NT 10.0.15031
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! redux-react-starter@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run web" "npm run rest" `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux-react-starter@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run web" "npm run rest" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redux-react-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "npm run tsc:w" "npm run web" "npm run rest"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redux-react-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls redux-react-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Code\ReactJS\UsingReactWithRedux\using-react-with-redux-master\npm-debug.log

npm ERR! path C:\Code\ReactJS\UsingReactWithRedux\using-react-with-redux-master\node_modules\.staging\os-homedir-8d857cc0\package.json.4027847783
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Code\ReactJS\UsingReactWithRedux\using-react-with-redux-master\node_modules\.staging\os-homedir-8d857cc0\package.json.4027847783' -> 'C:\Code\ReactJS\UsingReactWithRedux\using-react-with-redux-master\node_modules\.staging\os-homedir-8d857cc0\package.json'
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Code\ReactJS\UsingReactWithRedux\using-react-with-redux-master\node_modules\.staging\os-homedir-8d857cc0\package.json.4027847783' -> 'C:\Code\ReactJS\UsingReactWithRedux\using-react-with-redux-master\node_modules\.staging\os-homedir-8d857cc0\package.json'
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Code\\ReactJS\\UsingReactWithRedux\\using-react-with-redux-master\\node_modules\\.staging\\os-homedir-8d857cc0\\package.json.4027847783',
npm ERR!   dest: 'C:\\Code\\ReactJS\\UsingReactWithRedux\\using-react-with-redux-master\\node_modules\\.staging\\os-homedir-8d857cc0\\package.json',
npm ERR!   parent: 'redux-react-starter' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Code\ReactJS\UsingReactWithRedux\using-react-with-redux-master\npm-debug.log

However this is running as administrator,

**Comment by ericwgreene** [comment]
This looks like a permission issue. The installation of the actual NPM packages is done by NPM not the project itself. NPM is most likely working correctly, it simply does not have permissions to write/modify files in the folders it needs to. I would double check your permissions. Do not assume that because you admin it will just work. Windows can act a little odd with file permissions even when you think you are running as administrator.

**Comment by S3curityPlu5** [comment]
Yes I fixed it thanks

**Comment by ericwgreene** [comment]
Excellent! Have fun!
