### ISSUE TITLE
Will not run possibly due to Type error

### ISSUE THREAD

**Issue by aikidoshi** [training4developers/using-react-with-redux#2]
$ yarn start
yarn start v0.24.4
$ tsc && concurrently "npm run tsc:w" "npm run web" "npm run rest"
typings/modules/react-dom/index.d.ts(165,11): error TS2559: Type 'Component<P, S>' has no properties in common with type 'ComponentLifecycle<P, S>'.
typings/modules/react/index.d.ts(165,11): error TS2559: Type 'Component<P, S>' has no properties in common with type 'ComponentLifecycle<P, S>'.
error Command failed with exit code 2.

[npm-debug.zip](https://github.com/training4developers/using-react-with-redux/files/1198911/npm-debug.zip)

**Comment by ericwgreene** [comment]
Pushed the fix. The issue was the default semantic verison of package.json dependencies. I locked it down to the exact version. Should work fine now.

**Comment by aikidoshi** [comment]
Fantastic response time, thanks Eric! That worked, so now back to the course video on https://mva.microsoft.com/en-US/training-courses/using-react-with-redux, many thanks.

**Comment by aikidoshi** [comment]
Great course too Eric! I'm quite familiar with react/redux but not using TypeScript, so i learned a lot. Thanks again.

**Comment by ericwgreene** [comment]
Thank you for the kind words! I am glad you enjoyed the video! We need to create some updated ones as TypeScript has changed a little in its more recent versions. If you have any suggestions for improvement, please do not hesitate to share them! Thanks!

**Comment by aikidoshi** [comment]
I'm too much of a Typescript novice to make much in the way of suggestions on that front, but if you do an update on the changes I'd appreciate a heads-up.


I'd also like to know how to integrate React into an MVC .NET app with a Web API built in. I've done a few hybrid projects using AngularJS for the front-end but now I want to use React & TypeScript instead, but not lose the level of integration with the API and the ease of deployment Visual Studio/Web Deploy offers.


I've about 5 React/Redux apps in production now, but had to have the API as a separate component, with the React manually deployed and it's a bit of a pain.


Regards,

Steve


________________________________
